<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.jingfang.cloud</groupId>
        <artifactId>jingfang-cloud-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>jingfang-cloud-starters</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>jingfang-cloud-starter-feign</module>
        <module>jingfang-cloud-starter-core</module>
        <module>jingfang-cloud-starter-dependencies</module>
        <module>jingfang-cloud-starter-mybatis</module>
        <module>jingfang-cloud-starter-redis</module>
        <module>jingfang-cloud-starter-sercurity</module>
        <module>jingfang-cloud-starter-oss</module>
        <module>jingfang-cloud-starter-logger</module>
        <module>jingfang-cloud-starter-web</module>
        <module>jingfang-cloud-starter-swagger</module>
        <module>jingfang-cloud-starter-actuator</module>
        <module>jingfang-cloud-starter-plugin</module>
        <module>jingfang-cloud-starter-lucene</module>
        <module>jingfang-cloud-starter-datasource</module>
        <module>jingfang-cloud-starter-liquibase</module>
        <module>jingfang-cloud-starter-websocket</module>
        <module>jingfang-cloud-starter-kafka</module>
        <module>jingfang-cloud-starter-gateway</module>
        <module>jingfang-cloud-starter-test</module>
        <module>jingfang-cloud-starter-dubbo</module>
    </modules>

</project>