server.servlet.encoding.enabled=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.force-response=true
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.name=jf-cookie-sid
server.servlet.session.cookie.path=/
server.servlet.session.persistent=false
server.compression.enabled=true
server.compression.min-response-size=2MB
#spring cloud
spring.cloud.inetutils.ignoredInterfaces=docker0,veth.*
spring.cloud.nacos.config.file-extension=yaml
spring.cloud.nacos.config.group=${NACOS_GROUP:${spring.profiles.active:default}}
spring.cloud.nacos.config.namespace=${NACOS_NAMESPACE:${spring.profiles.active:default}}
spring.cloud.nacos.config.server-addr=${NACOS_SERVER:127.0.0.1}:${NACOS_PORT:8848}
spring.cloud.nacos.discovery.group=${NACOS_GROUP:${spring.profiles.active:default}}
spring.cloud.nacos.discovery.namespace=${NACOS_NAMESPACE:${spring.profiles.active:default}}
spring.cloud.nacos.discovery.server-addr=${NACOS_SERVER:127.0.0.1}:${NACOS_PORT:8848}
spring.config.import=nacos:${spring.application.name}:yaml
feign.okhttp.enabled=true
feign.httpclient.enabled=false
spring.devtools.livereload.port=0
spring.liquibase.enabled=false
spring.main.allow-bean-definition-overriding=true
management.endpoints.web.exposure.include=health,prometheus
management.server.port=${METRICS_PORT:${server.port:0}}
management.endpoints.web.base-path=/app/info
management.server.ssl.enabled=false
management.health.defaults.enabled=false
management.health.db.enabled=true
management.health.ping.enabled=true
management.health.redis.enabled=true
management.health.refresh.enabled=true
management.health.hystrix.enabled=false
management.health.influxdb.enabled=true
management.health.diskspace.enabled=true
management.endpoint.health.show-details=ALWAYS
management.endpoint.health.show-components=ALWAYS
management.endpoint.dubbo.enabled=true
management.endpoint.dubbo.dubboconfigs.enabled=true
management.endpoint.dubbo.dubboshutdown.enabled=false
management.endpoint.dubbo.dubboservices.enabled=true
management.endpoint.dubbo.dubboreferences.enabled=true
management.endpoint.dubbo.dubboproperties.enabled=true
management.prometheus.metrics.export.enabled=true
springfox.documentation.auto-startup=false
mybatis-plus.global-config.banner=false
logging.file.name=/logs/server.log
spring.boot.admin.client.instance.prefer-ip=true
spring.cloud.discovery.client.composite-indicator.enabled=false
springdoc.api-docs.enabled=${jingfang.api-docs.enabled}
springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json
info.projectId=${jingfang.server.projectId}
info.environmentId=${jingfang.server.environmentId}
spring.autoconfigure.exclude=\
  com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceAutoConfiguration, \
  org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration, \
  org.springframework.boot.autoconfigure.context.MessageSourceAutoConfiguration, \
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, \
  org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration, \
  com.alibaba.cloud.dubbo.autoconfigure.DubboOpenFeignAutoConfiguration, \
  com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration, \
  org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration


