<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.jingfang.cloud</groupId>
        <artifactId>jingfang-cloud-starters</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>jingfang-cloud-starter-dependencies</artifactId>
    <packaging>pom</packaging>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.jingfang.cloud</groupId>
                <artifactId>jingfang-cloud-starter-core</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jingfang.cloud</groupId>
                <artifactId>jingfang-cloud-starter-gateway</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jingfang.cloud</groupId>
                <artifactId>jingfang-cloud-starter-feign</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jingfang.cloud</groupId>
                <artifactId>jingfang-cloud-starter-actuator</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jingfang.cloud</groupId>
                <artifactId>jingfang-cloud-starter-datasource</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jingfang.cloud</groupId>
                <artifactId>jingfang-cloud-starter-liquibase</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jingfang.cloud</groupId>
                <artifactId>jingfang-cloud-starter-logger</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jingfang.cloud</groupId>
                <artifactId>jingfang-cloud-starter-lucene</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jingfang.cloud</groupId>
                <artifactId>jingfang-cloud-starter-minio</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jingfang.cloud</groupId>
                <artifactId>jingfang-cloud-starter-mybatis</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jingfang.cloud</groupId>
                <artifactId>jingfang-cloud-starter-plugin</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jingfang.cloud</groupId>
                <artifactId>jingfang-cloud-starter-redis</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jingfang.cloud</groupId>
                <artifactId>jingfang-cloud-starter-sercurity</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jingfang.cloud</groupId>
                <artifactId>jingfang-cloud-starter-swagger</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jingfang.cloud</groupId>
                <artifactId>jingfang-cloud-starter-web</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jingfang.cloud</groupId>
                <artifactId>jingfang-cloud-starter-websocket</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <distributionManagement>
        <repository>
            <id>maven-releases</id>
            <name>releases</name>
            <url>http://192.168.130.243:8081/repository/maven-releases/</url>
        </repository>
        <snapshotRepository>
            <id>maven-snapshots</id>
            <name>snapshots</name>
            <url>http://192.168.130.243:8081/repository/maven-snapshots/</url>
        </snapshotRepository>
    </distributionManagement>

</project>
