#\u5141\u8BB8\u66FF\u6362\u7684\u9ED8\u8BA4\u503C
server:
  servlet:
    session:
      persistent: false
      tracking-modes: COOKIE
  # undertow 配置
  undertow:
    # HTTP post内容的最大大小。当值为-1时，默认值为大小是无限的
    max-http-post-size: -1
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 512
    # 是否分配的直接内存
    direct-buffers: true
    threads:
      # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      io: 8
      # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
      worker: 256
feign:
  client:
    config:
      default:
        read-timeout: 3000
        connect-timeout: 2000
dubbo:
  cloud:
    subscribed-services:
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  protocols:
    dubbo:
      port: -1
      serialization: kryo
  consumer:
    check: false
  registry:
    address: 'nacos://${spring.cloud.nacos.discovery.server-addr}?username=${spring.cloud.nacos.username}&password=${spring.cloud.nacos.password}'
    group: ${spring.cloud.nacos.discovery.group}
    parameters:
      namespace: ${spring.cloud.nacos.discovery.namespace}
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    hikari:
      connection-test-query: 'SELECT 1 FROM DUAL'
  web:
    resources:
      static-locations:
        - file:/opt/resources/${spring.application.name}/dist
        - file:C:/opt/resources/${spring.application.name}/dist
        - file:C:/opt/resources/
        - file:/opt/resources/
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    mode: ${spring.redis.model:STANDALONE}
xxl:
  job:
    executor:
      app-name: ${spring.application.name}
      ip-address: ${spring.cloud.client.ip-address}
  level:
    'com.jingfang.cloud': INFO
    'org.apache.kafka.clients.producer.ProducerConfig': 'OFF'
    'org.apache.kafka.clients.consumer.ConsumerConfig': 'OFF'
    'org.springframework.boot.actuate.endpoint.EndpointId': 'OFF'
    'com.baomidou.mybatisplus.core.metadata.TableInfoHelper': 'ERROR'
    'com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder': 'OFF'
    'org.springframework.cloud.client.discovery.DiscoveryClient': 'OFF'
    'org.springframework.boot.web.embedded.tomcat.TomcatWebServer': 'INFO'
    'org.springframework.context.support.ResourceBundleMessageSource': 'ERROR'
    'org.springframework.jmx.export.annotation.AnnotationMBeanExporter': 'ERROR'
    'org.springframework.context.annotation.ConfigurationClassPostProcessor': 'OFF'
    'org.springframework.context.annotation.AnnotationConfigApplicationContext': 'OFF'
    'org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver': 'ERROR'
    'liquibase.lockservice': 'INFO'

# MyBatisPlus配置
mybatis-plus:
  mapperPackage: ${jingfang.mybatis.mapperPackage:com.jingfang.cloud.**.mapper}
  typeAliasesPackage: ${jingfang.mybatis.typeAliasesPackage:com.jingfang.cloud.**.domain}
  checkConfigLocation: false
  configuration:
    mapUnderscoreToCamelCase: true
    # MyBatis 自动映射策略
    # NONE：不启用 PARTIAL：只对非嵌套 resultMap 自动映射 FULL：对所有 resultMap 自动映射
    autoMappingBehavior: PARTIAL
    # MyBatis 自动映射时未知列或未知属性处理策
    # NONE：不做处理 WARNING：打印相关警告 FAILING：抛出异常和详细信息
    autoMappingUnknownColumnBehavior: NONE
    # 更详细的日志输出 会有性能损耗 org.apache.ibatis.logging.stdout.StdOutImpl
    # 关闭日志记录 (可单纯使用 p6spy 分析) org.apache.ibatis.logging.nologging.NoLoggingImpl
    # 默认日志输出 org.apache.ibatis.logging.slf4j.Slf4jImpl
    logImpl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    # 是否打印 Logo banner
    banner: true
    dbConfig:
      idType: ASSIGN_ID
      logicDeleteValue: 1
      logicNotDeleteValue: 0
      insertStrategy: NOT_NULL
      updateStrategy: NOT_NULL
      where-strategy: NOT_NULL
jingfang:
  security:
    sa-token:
      token-name: Authorization
      token-prefix: Bearer
      token-style: random-64
      timeout: 4363200
      jwt-secret-key: jf-token-secret
      active-timeout: -1
      is-share: true
      is-print: false
      is-concurrent: true
  api-docs:
    enabled: true
    title: "${spring.application.name} Api Documents"
  liquibase:
    enabled: true
    url: ${spring.datasource.url:${spring.shardingsphere.datasource.master.jdbc-url}}
    username: ${spring.datasource.username:${spring.shardingsphere.datasource.master.username}}
    password: ${spring.datasource.password:${spring.shardingsphere.datasource.master.password}}
    driver-class-name: ${spring.datasource.driver-class-name:${spring.shardingsphere.datasource.master.driver-class-name}}
