server:
  servlet:
    session:
      persistent: false
      tracking-modes: COOKIE
  undertow:
    max-http-post-size: -1
    buffer-size: 512
    direct-buffers: true
    threads:
      io: 8
      worker: 256
feign:
  client:
    config:
      default:
        read-timeout: 3000
        connect-timeout: 2000
dubbo:
  cloud:
    subscribed-services:
  protocol:
    name: dubbo
    port: -1
  protocols:
    dubbo:
      port: -1
  consumer:
    check: false
  registry:
    address: 'nacos://${spring.cloud.nacos.discovery.server-addr}?username=${spring.cloud.nacos.username}&password=${spring.cloud.nacos.password}'
    group: ${DUBBO_GROUP:DUBBO_GROUP}
    parameters:
      namespace: ${DUBBO_NAMESPACE:public}
spring:
  config:
    import: "optional:dbconfig:"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    hikari:
      connection-test-query: 'SELECT 1 FROM DUAL'
  web:
    resources:
      static-locations:
        - file:/opt/resources/${spring.application.name}/dist
        - file:C:/opt/resources/${spring.application.name}/dist
        - file:C:/opt/resources/
        - file:/opt/resources/
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    mode: ${spring.redis.model:STANDALONE}
xxl:
  job:
    executor:
      app-name: ${spring.application.name}
      ip-address: ${spring.cloud.client.ip-address}
  level:
    'com.lambda.cloud': INFO
    'org.apache.kafka.clients.producer.ProducerConfig': 'OFF'
    'org.apache.kafka.clients.consumer.ConsumerConfig': 'OFF'
    'org.springframework.boot.actuate.endpoint.EndpointId': 'OFF'
    'com.baomidou.mybatisplus.core.metadata.TableInfoHelper': 'ERROR'
    'com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder': 'OFF'
    'org.springframework.cloud.client.discovery.DiscoveryClient': 'OFF'
    'org.springframework.boot.web.embedded.tomcat.TomcatWebServer': 'INFO'
    'org.springframework.context.support.ResourceBundleMessageSource': 'ERROR'
    'org.springframework.jmx.export.annotation.AnnotationMBeanExporter': 'ERROR'
    'org.springframework.context.annotation.ConfigurationClassPostProcessor': 'OFF'
    'org.springframework.context.annotation.AnnotationConfigApplicationContext': 'OFF'
    'org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver': 'ERROR'
    'liquibase.lockservice': 'INFO'
# MyBatisPlus配置
mybatis-plus:
  checkConfigLocation: false
  configuration:
    mapUnderscoreToCamelCase: true
    autoMappingBehavior: PARTIAL
    autoMappingUnknownColumnBehavior: NONE
    logImpl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    banner: true
    dbConfig:
      idType: ASSIGN_ID
      logicDeleteValue: 1
      logicNotDeleteValue: 0
      insertStrategy: NOT_NULL
      updateStrategy: NOT_NULL
      where-strategy: NOT_NULL
lambda:
  security:
    sa-token:
      token-name: Authorization
      token-prefix: Bearer
      token-style: random-64
      timeout: 4363200
      jwt-secret-key: lambda-token-secret
      active-timeout: -1
      is-share: true
      is-print: false
      is-concurrent: true
  api-docs:
    title: "${spring.application.name} Api Documents"
