<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.lambda.cloud</groupId>
        <artifactId>lambda-cloud-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>lambda-cloud-starter-dependencies</artifactId>
    <packaging>pom</packaging>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.lambda.cloud</groupId>
                <artifactId>lambda-cloud-core</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lambda.cloud</groupId>
                <artifactId>lambda-cloud-starter-dubbo</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lambda.cloud</groupId>
                <artifactId>lambda-cloud-starter-gateway</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lambda.cloud</groupId>
                <artifactId>lambda-cloud-starter-feign</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lambda.cloud</groupId>
                <artifactId>lambda-cloud-starter-actuator</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lambda.cloud</groupId>
                <artifactId>lambda-cloud-starter-datasource</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lambda.cloud</groupId>
                <artifactId>lambda-cloud-starter-liquibase</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lambda.cloud</groupId>
                <artifactId>lambda-cloud-starter-logger</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lambda.cloud</groupId>
                <artifactId>lambda-cloud-starter-oss</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lambda.cloud</groupId>
                <artifactId>lambda-cloud-starter-mybatis</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lambda.cloud</groupId>
                <artifactId>lambda-cloud-starter-redis</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lambda.cloud</groupId>
                <artifactId>lambda-cloud-starter-sercurity</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lambda.cloud</groupId>
                <artifactId>lambda-cloud-starter-swagger</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lambda.cloud</groupId>
                <artifactId>lambda-cloud-starter-web</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lambda.cloud</groupId>
                <artifactId>lambda-cloud-starter-websocket</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lambda.cloud</groupId>
                <artifactId>lambda-cloud-starter-sms</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lambda.cloud</groupId>
                <artifactId>lambda-cloud-starter-rocketmq</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
